export const SEARCH_STARTED="SEARCH_STARTED"
export const SEARCH_COMPLETED="SEARCH_COMPLETED"
export const SEARCH_FAILED="SEARCH_FAILED"

export const EDIT_STARTED="EDIT_STARTED"
export const EDIT_COMPLETED="EDIT_COMPLETED"
export const EDIT_FAILED="EDIT_FAILED"

export const DELETE_STARTED="DELETE_STARTED"
export const DELETE_COMPLETED="DELETE_COMPLETED"
export const DELETE_FAILED="DELETE_FAILED"